DROP TABLE IF EXISTS todos;

 CREATE TABLE IF NOT EXISTS doing (
    id INT GENERATED ALWAYS AS IDENTITY,
    todo VARCHAR(140) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS completed (
    id INT GENERATED ALWAYS AS IDENTITY,
    complete VARCHAR(140) NOT NULL,
    PRIMARY KEY (id)
);
